external_components:
  - source:
      type: git
      url: https://github.com/kalanchoej/mpu6050_esphome
      ref: main 
    components: [mpu6050_custom]

custom_component:
  - id: mpu6050_sensor
    type: MPU6050Custom
    interrupt_pin: 10  # Example GPIO pin for interrupt
    sensitivity: "medium"
    duration: "short"
